spring:
  profiles:
    active: local
  datasource:
    # url: jdbc:h2:tcp://localhost/~/toy_db
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  h2:
    console:
      enabled: true